name = "template"
main = "./build/server/index.js"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

kv_namespaces = [
  { binding = "cache", id = "cache" }
]

[assets]
directory = "./build/client"

[build]
command = "npm run build"