name = "template"
main = "./build/server/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[assets]
directory = "./build/client"

[build]
command = "npm run build"
