name = "template"
main = "./build/server/index.js"
workers_dev = true
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]  # Tambahkan flag ini

kv_namespaces = [
  { binding = "cache", id = "cache" }
]

[assets]
directory = "./build/client"

[build]
command = "npm run build"