#:schema node_modules/wrangler/config-schema.json
name = "template"
main = "./server.ts"
workers_dev = true
main = "./build/server/index.js"
assets = { directory = "./build/client/" }
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

kv_namespaces = [{ binding = "cache", id = "cache" }]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "npm run build"