name = "template"
main = "./build/server/index.js" # Hanya satu definisi main
workers_dev = true
compatibility_date = "2024-09-26"

kv_namespaces = [
  { binding = "cache", id = "cache" }
]

[assets]
directory = "./build/client"

[build]
command = "npm run build"
